[DEFAULT]
mongodb_uri = "mongodb+srv://vijaymiiyath4300:ATIwRvZnqu5d92S6@cluster0.0ae4h.mongodb.net/?retryWrites=true&w=majority"
mongodb_database = "datasyncx_db"
mongodb_log_database = "datasyncx_logs"
mongodb_collection = "dhr_documents"
mongodb_log_activity_info_collection = "activity_info"
mongodb_log_pair_history_collection = "pair_history"
mongodb_log_history_collection = "processing_history"
mongodb_log_email_collection = "email_logs"
mongodb_log_s3_collection = "s3_logs"
pickup_folder = "tmp/pickup/"

[credentials]
username1 = "vijay"
username2 = "suriya"
password = "datasyncx"